### PR TITLE
Fixes and additions

### PR DESCRIPTION
**Pull request by Gitoffomalawn**
- Fixed MySQL issues with docker-compose
- Added new environment variables
- Updated README

### CODE REVIEW

**Review by kpeiruza — COMMENTED** [review]
Please, keep the volumes as named volumes instead of local paths. IMO it's a bit safer and cleaner.

I like the change from mysql to mariadb. Have you tried an even newer version of mariadb?

**Review by kpeiruza — CHANGES_REQUESTED** [review]
Are you sure that echo's for APACHE CONFIG work?

As far as I can recall, that 000-default.conf ends with </VirtualHost> so this directive would be outside of the VirtualHost.

Besiders, that's cleaner with just 1 echo '' or a cat <EOF.

In any case, why do you need AllowOverride All if you aren't creating a .htaccess or similar?

You can achieve the same with a sed -i, isn't it?

The rest looks great :-)

**Review by kpeiruza — COMMENTED** [review]
Will get approved once the PR containing the HTP block is accepted.

Thanks again!

**Comment by Gitoffomalawn** [comment]
> Please, keep the volumes as named volumes instead of local paths. IMO it's a bit safer and cleaner.

You're right. I just copied and pasted my `docker-compose.yaml` after getting everything to work. For experiments I like to keep everything contained to one folder I can then easily get rid of. Forgot to change those back.

> I like the change from mysql to mariadb. Have you tried an even newer version of mariadb?

I have not . I was trying for hours to solve the MySQL problems using the `mysql:5.7` image, when I finally gave up and switched to a MariaDB version I thought would work (which it did, on the first try). After that I didn't really feel like experimenting with the images any further. 

It should work though, depending on the default authentication mechanism employed by MariaDB. If they didn't go the route that MySQL went in with 8.0+ with the SHA2 hash logins but stuck with password-based authentication in more recent MariaDB versions, I don't see why it shouldn't work. I knew that `martiadb:5.5` uses this, which is why I was confident it would present a minimal shift from `mysql:5.7`.

ETA: Just did a quick test with `mariadb:latest`. It works just fine, and, arguably, much faster than `mariadb:5.5`. That said, it'll probably be best to choose a fixed image for the sake of stability.

> Are you sure that echo's for APACHE CONFIG work?
> 
> As far as I can recall, that 000-default.conf ends with so this directive would be outside of the VirtualHost.
> 
> Besiders, that's cleaner with just 1 echo '' or a cat <EOF.
> 
> In any case, why do you need AllowOverride All if you aren't creating a .htaccess or similar?
> 
> You can achieve the same with a sed -i, isn't it?

The echos work. Though I'll admit I'm unsure whether they are strictly necessary. In my quest to add missing environment parameters to the `entrypoint.sh` I just followed the steps in [the Hashtopolis setup video](https://www.youtube.com/watch?v=O08gddjVbfc) posted by its maintainer, which specifically mentions these additions in this place. By the time I got to that point, and not being 100% with how the docker image functions, I was in a "if it doesn't help, it surely can't hurt" state of mind. If they aren't necessary, I'm more than happy to remove them.

> The rest looks great :-)

Thanks. and no problem, man. These are the kind of projects that are super handy, and very under-supported. Being able to roll out Hashtopolis in just a few minutes with little to no manual interventions (you still need to change file permissions on the volumes after the container goes up) is super handy.

**Review by kpeiruza — APPROVED** [review]
Thanks!

**Comment by Gitoffomalawn** [comment]
> Thanks!

No problem, man. I'm also going to look into making the README a bit more easy to follow, since the instructions aren't very clear, and some steps and information are missing. But I'll do a separate PR for that. Keeps things manageable.

**Comment by kpeiruza** [comment]
> > Please, keep the volumes as named volumes instead of local paths. IMO it's a bit safer and cleaner.
> 
> You're right. I just copied and pasted my `docker-compose.yaml` after getting everything to work. For experiments I like to keep everything contained to one folder I can then easily get rid of. Forgot to change those back.
> 
> > I like the change from mysql to mariadb. Have you tried an even newer version of mariadb?
> 
> I have not . I was trying for hours to solve the MySQL problems using the `mysql:5.7` image, when I finally gave up and switched to a MariaDB version I thought would work (which it did, on the first try). After that I didn't really feel like experimenting with the images any further.
> 
> It should work though, depending on the default authentication mechanism employed by MariaDB. If they didn't go the route that MySQL went in with 8.0+ with the SHA2 hash logins but stuck with password-based authentication in more recent MariaDB versions, I don't see why it shouldn't work. I knew that `martiadb:5.5` uses this, which is why I was confident it would present a minimal shift from `mysql:5.7`.
> 
> ETA: Just did a quick test with `mariadb:latest`. It works just fine, and, arguably, much faster than `mariadb:5.5`. That said, it'll probably be best to choose a fixed image for the sake of stability.
> 
> > Are you sure that echo's for APACHE CONFIG work?
> > As far as I can recall, that 000-default.conf ends with so this directive would be outside of the VirtualHost.
> > Besiders, that's cleaner with just 1 echo '' or a cat <EOF.
> > In any case, why do you need AllowOverride All if you aren't creating a .htaccess or similar?
> > You can achieve the same with a sed -i, isn't it?
> 
> The echos work. Though I'll admit I'm unsure whether they are strictly necessary. In my quest to add missing environment parameters to the `entrypoint.sh` I just followed the steps in [the Hashtopolis setup video](https://www.youtube.com/watch?v=O08gddjVbfc) posted by its maintainer, which specifically mentions these additions in this place. By the time I got to that point, and not being 100% with how the docker image functions, I was in a "if it doesn't help, it surely can't hurt" state of mind. If they aren't necessary, I'm more than happy to remove them.
> 
> > The rest looks great :-)
> 
> Thanks. and no problem, man. These are the kind of projects that are super handy, and very under-supported. Being able to roll out Hashtopolis in just a few minutes with little to no manual interventions (you still need to change file permissions on the volumes after the container goes up) is super handy.

-------------------

It's lovely to see people using this docker and finding it useful :-)

**Comment by Gitoffomalawn** [comment]
> It's lovely to see people using this docker and finding it useful :-)

For sure. Let me know if there's anything else I need to do for this PR.

**Comment by kpeiruza** [comment]
For this PR, just that.

Feel free to make a proper README.md, I'm not a native English speaker.



Missatge de Gitoffomalawn ***@***.***> del dia dv., 5 de maig
2023 a les 12:00:

**Comment by Gitoffomalawn** [comment]
> For this PR, just that.

By that, did you mean the volume names? Or did you want me to remove/modify the `000-default.conf` echos too?

> Feel free to make a proper README.md, I'm not a native English speaker.

No problem. I'll see if I can sink some time into it.

**Review by kpeiruza — APPROVED** [review]

**Comment by kpeiruza** [comment]
New Docker image pushed, Hashtopolis has been updated as well, please try
it out, I'm on a bit busy day....

Thanks!

**Pull request merged**
